spring.application.name=backend-api

spring.datasource.url=jdbc:postgresql://localhost:5432/energy_communities
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver