spring.application.name=percentage-service

spring.main.web-application-type=none

spring.datasource.url=jdbc:postgresql://localhost:5432/energy_communities
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=disysuser
spring.rabbitmq.password=disyspw

app.rabbitmq.queue.usage-updates=usage.updates