spring.application.name=community-producer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=disysuser
spring.rabbitmq.password=disyspw

energy.queue.name=energy.messages
