spring.application.name=usage-service

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=disysuser
spring.rabbitmq.password=disyspw

spring.datasource.url=jdbc:postgresql://localhost:5432/energy_communities
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

energy.queue.name=energy.messages
usage.update.queue.name=usage.updates
